context:
  version: 0.3.2

package:
  name: xeus-javascript
  version: '{{ version }}'

source:
  url: https://github.com/jupyter-xeus/xeus-javascript/archive/refs/tags/{{ version }}.tar.gz
  sha256: 195d03bd8669084f56d2a1a3dd0de7a7a1c5d40498013eae98e639a01f02c9db

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - nlohmann_json
    - xeus-lite
    - xeus >=3.0.5,<4.0
    - xtl >=0.7

test:
  commands:
    - sel(emscripten): test -f $PREFIX/bin/xjavascript.wasm
    - sel(emscripten): test -f $PREFIX/bin/xjavascript.js

about:
  home: https://github.com/jupyter-xeus/xeus-javascript
  license: BSD-3
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-javascript
  doc_url: https://github.com/jupyter-xeus/xeus-javascript
  dev_url: https://github.com/jupyter-xeus/xeus-javascript

extra:
  recipe-maintainers:
    - DerThorsten
