context:
  name: numcodecs
  version: '0.12.1'

package:
  name: numcodecs
  version: '{{ version }}'

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 05d91a433733e7eef268d7e80ec226a0232da244289614a8f3826901aec1098e
    patches:
      - patches/fixblosc.patch
      - patches/fixsetup.patch
      - patches/fixzlib.patch
  - path: setup.py

build:
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
    - cross-python_emscripten-wasm32
    - cython
    - python
    - pip
    - setuptools_scm
  host:
    - python
  run:
    - numpy
    - msgpack

extra:
  emscripten_tests:
    python:
      pytest_files:
        - test_import_numcodecs.py
