context:
  version: 2.0.16

package:
  name: sqlalchemy
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/S/SQLAlchemy/SQLAlchemy-${{ version }}.tar.gz
  sha256: 1e2caba78e7d1f5003e88817b7a1754d4e58f4a8f956dc423bf8e304c568ab09

build:
  number: 0

requirements:
  build:
  - python                                   # [build_platform != target_platform]
  - cross-python_${{ target_platform }}      # [build_platform != target_platform]
  - ${{ compiler('c') }}
  - pip
  host:
  - python
  run:
  - python
  - typing-extensions

tests:
- script: pytester
  files:
    recipe:
    - test_import_sqlalchemy.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
about:
  summary: Database Abstraction Library
  license: MIT

  homepage: https://www.sqlalchemy.org
