context:
  version: 2.0.8

package:
  name: sqlalchemy
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/S/SQLAlchemy/SQLAlchemy-{{ version }}.tar.gz
  sha256: 250e158a1f36c965dde1f949366eae9a57504a8cd7a4d968e66c2d0b3c18198d

build:
  number: 0

requirements:
  build:
  - python                                   # [build_platform != target_platform]
  - cross-python_{{ target_platform }}       # [build_platform != target_platform]
  - "{{ compiler('c') }}"
  - pip
  host:
  - python
  run:
  - python
  - typing-extensions

about:
  home: https://www.sqlalchemy.org
  summary: Database Abstraction Library
  license: MIT

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_import_sqlalchemy.py
