context:
  version: 2.0.15

package:
  name: sqlalchemy
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/S/SQLAlchemy/SQLAlchemy-${{ version }}.tar.gz
  sha256: 2e940a8659ef870ae10e0d9e2a6d5aaddf0ff6e91f7d0d7732afc9e8c4be9bbc

build:
  number: 0

requirements:
  build:
  - python                                   # [build_platform != target_platform]
  - cross-python_${{ target_platform }}      # [build_platform != target_platform]
  - ${{ compiler('c') }}
  - pip
  host:
  - python
  run:
  - python
  - typing-extensions

tests:
- script: pytester
  files:
    recipe:
    - test_import_sqlalchemy.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
about:
  summary: Database Abstraction Library
  license: MIT

  homepage: https://www.sqlalchemy.org
