context:
  version: 5.0.6

package:
  name: swiglpk
  version: ${{ version }}

source:
- url: https://github.com/biosustain/swiglpk/archive/refs/tags/${{ version }}.tar.gz
  sha256: ad293cb0ede889bbec7beae90c50cb13ee2c9c3617f7c199b76fa709e0366759

build:
  number: 0

requirements:
  build:
  - cross-python_emscripten-wasm32
  - python
  - swig
  - pip
  host:
  - python
  - glpk

tests:
- script: pytester
  files:
    recipe:
    - test_import_swiglpk.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
