context:
  version: 5.0.9

package:
  name: swiglpk
  version: ${{ version }}

source:
- url: https://github.com/biosustain/swiglpk/archive/refs/tags/${{ version }}.tar.gz
  sha256: 2aa9f61d78802acce655dbca8670ce2281da97cdc90b212f694b254dc38c8670

build:
  number: 0

requirements:
  build:
  - cross-python_emscripten-wasm32
  - python
  - swig
  - pip
  host:
  - python
  - glpk

tests:
- script: pytester
  files:
    recipe:
    - test_import_swiglpk.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
