context:
  name: fontconfig
  version: 2.13.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: http://www.freedesktop.org/software/${{ name }}/release/${{ name }}-${{ version }}.tar.gz
  sha256: a6ca290637d8b2c4e1dd40549b179202977593f7481ec83ddfb1765ad90037ba
  patches:
  - patches/syscache-always-valid.diff

build:
  number: 0

requirements:
  build:
  - ${{ compiler('c') }}
  - pkg-config
  - gperf
  - libuuid
  host:
  - freetype
  - expat
      # - xml2 (TODO - or just use expat)
    # - freetype
    # - libiconv  # [win]
    # - libuuid   # [linux]
    # - zlib

tests:
- script:
  - test -f $PREFIX/lib/libfontconfig.a
  - test -f $PREFIX/include/fontconfig/fontconfig.h
  - node $PREFIX/bin/fc-cache --version
  - node $PREFIX/bin/fc-cat --version
  - node $PREFIX/bin/fc-list --version
  - node $PREFIX/bin/fc-match --version
  - node $PREFIX/bin/fc-pattern --version
  - node $PREFIX/bin/fc-query --version
  - node $PREFIX/bin/fc-scan --version
  - node $PREFIX/bin/fc-validate --version
  requirements:
    build:
    - nodejs

about:
  homepage: http://www.freedesktop.org/wiki/Software/fontconfig/
  license: MIT
  license_file: COPYING
  summary: A library for configuring and customizing font access
  description: |
    Fontconfig is a library designed to provide system-wide font configuration,
    customization and application access.
  documentation: https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
  repository: https://cgit.freedesktop.org/fontconfig/
