context:
  version: 1.1.40

package:
  name: libxslt
  version: ${{ version }}

source:
  url: https://download.gnome.org/sources/libxslt/${{ version[0:3] }}/libxslt-${{
    version }}.tar.xz
  sha256: 194715db023035f65fb566402f2ad2b5eab4c29d541f511305c40b29b1f48d13

build:
  number: 1

requirements:
  build:
  - ${{ compiler("c") }}
  - gnuconfig
  host:
  - libxml2
  - zlib
  run:
  - libxml2
